import { connect, connection } from "mongoose";
import { UserSchema } from "../common/schemas/user.schema";

const MONGO_URI = process.env.MONGO_URI || "mongodb://localhost:27017/pranayam";

// Comprehensive profile data - realistic Indian profiles
const dummyUsers = [
  {
    firebaseUid: "seed_user_001",
    name: "Aparna Nair",
    phoneNumber: "+919876543001",
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400",
    photos: [
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400",
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400",
      "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400",
    ],
    bio: "Software engineer at Google who loves to explore Kerala backwaters on weekends. Looking for someone who appreciates both code and chai conversations. Fluent in sarcasm and Python.",
    gender: "FEMALE",
    location: { type: "Point", coordinates: [76.2711, 9.9312] },
    city: "Kochi",
    dob: new Date("1998-05-15"),
    age: 26,
    height: 165,
    jobTitle: "Senior Software Engineer",
    company: "Google",
    education: "M.Tech Computer Science",
    college: "IIT Madras",
    lookingFor: "LONG_TERM",
    drinking: "SOMETIMES",
    smoking: "NEVER",
    workout: "OFTEN",
    religion: "Hindu",
    languages: ["Malayalam", "English", "Hindi"],
    prompts: [
      { question: "A perfect day for me looks like", answer: "Morning yoga, brunch with friends, coding a passion project, and ending with a sunset at Marine Drive" },
      { question: "I'm looking for someone who", answer: "Can match my energy in deep conversations and comfortable silences equally" },
      { question: "My simple pleasures", answer: "Filter coffee, old Malayalam songs, and debugging code at 2 AM" },
    ],
    interests: ["Technology", "Travel", "Photography", "Coffee", "Yoga", "Reading"],
    isVerified: true,
    preferences: {
      distance: 50,
      ageRange: { min: 26, max: 34 },
      gender: ["MALE"],
    },
  },
  {
    firebaseUid: "seed_user_002",
    name: "Rahul Menon",
    phoneNumber: "+919876543002",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    photos: [
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400",
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400",
    ],
    bio: "Architect designing sustainable homes across Kerala. Weekend chef who believes the way to someone's heart is through their stomach. Can talk for hours about Ghibli films and Carnatic music.",
    gender: "MALE",
    location: { type: "Point", coordinates: [76.9366, 8.5241] },
    city: "Thiruvananthapuram",
    dob: new Date("1995-08-22"),
    age: 29,
    height: 178,
    jobTitle: "Principal Architect",
    company: "Self-employed",
    education: "B.Arch",
    college: "NIT Calicut",
    lookingFor: "LONG_TERM",
    drinking: "SOMETIMES",
    smoking: "NEVER",
    workout: "SOMETIMES",
    religion: "Hindu",
    languages: ["Malayalam", "English", "Tamil"],
    prompts: [
      { question: "I geek out on", answer: "Sustainable architecture, Studio Ghibli soundtracks, and the perfect dosa batter recipe" },
      { question: "The way to my heart is", answer: "Appreciate my cooking, watch Mani Ratnam movies with me, and laugh at my terrible puns" },
      { question: "On weekends you'll find me", answer: "At my drawing board, experimenting in the kitchen, or playing guitar on my balcony" },
    ],
    interests: ["Architecture", "Music", "Cooking", "Yoga", "Cinema", "Sustainability"],
    isVerified: true,
    preferences: {
      distance: 75,
      ageRange: { min: 24, max: 32 },
      gender: ["FEMALE"],
    },
  },
  {
    firebaseUid: "seed_user_003",
    name: "Priya Krishnan",
    phoneNumber: "+919876543003",
    photoUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400",
    photos: [
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400",
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400",
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400",
    ],
    bio: "Cardiologist saving hearts by day, watercolor artist by night. Love watching sunsets at Kozhikode beach with a good book. Looking for my person to share lazy Sunday mornings with.",
    gender: "FEMALE",
    location: { type: "Point", coordinates: [75.7804, 11.2588] },
    city: "Kozhikode",
    dob: new Date("1996-12-03"),
    age: 28,
    height: 160,
    jobTitle: "Cardiologist",
    company: "Aster MIMS Hospital",
    education: "MD Cardiology",
    college: "Govt. Medical College, Kozhikode",
    lookingFor: "LONG_TERM",
    drinking: "NEVER",
    smoking: "NEVER",
    workout: "SOMETIMES",
    religion: "Hindu",
    languages: ["Malayalam", "English", "Hindi"],
    prompts: [
      { question: "I'm convinced that", answer: "The best conversations happen over cutting chai at 4 PM" },
      { question: "My most controversial opinion", answer: "Biryani from Kozhikode is better than Hyderabad's (don't @ me)" },
      { question: "Green flags I look for", answer: "Kindness to strangers, a good sense of humor, and someone who reads" },
    ],
    interests: ["Art", "Reading", "Movies", "Travel", "Medicine", "Beaches"],
    isVerified: true,
    preferences: {
      distance: 100,
      ageRange: { min: 28, max: 36 },
      gender: ["MALE"],
    },
  },
  {
    firebaseUid: "seed_user_004",
    name: "Arjun Varma",
    phoneNumber: "+919876543004",
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400",
    photos: [
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400",
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400",
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400",
    ],
    bio: "Founder of a fintech startup that just got Series A. Recovering workaholic learning to enjoy life. Cricket fanatic who believes in Sachin supremacy. Looking for someone to share my success and failures with.",
    gender: "MALE",
    location: { type: "Point", coordinates: [76.2711, 9.9312] },
    city: "Kochi",
    dob: new Date("1993-03-18"),
    age: 31,
    height: 175,
    jobTitle: "Founder & CEO",
    company: "PayEase Technologies",
    education: "MBA Finance",
    college: "IIM Bangalore",
    lookingFor: "LONG_TERM",
    drinking: "SOMETIMES",
    smoking: "NEVER",
    workout: "OFTEN",
    religion: "Hindu",
    languages: ["Malayalam", "English", "Hindi", "Tamil"],
    prompts: [
      { question: "Two truths and a lie", answer: "I've pitched to Shark Tank India, I can cook Maggi in 47 ways, I've never missed a gym day (okay that's the lie)" },
      { question: "My love language is", answer: "Quality time and acts of service - I'll fix your laptop and make you coffee" },
      { question: "Best travel story", answer: "Got lost in Munnar, ended up at a local's home, left with their grandmother's chutney recipe" },
    ],
    interests: ["Technology", "Cricket", "Startups", "Coffee", "Fitness", "Investing"],
    isVerified: true,
    preferences: {
      distance: 50,
      ageRange: { min: 26, max: 32 },
      gender: ["FEMALE"],
    },
  },
  {
    firebaseUid: "seed_user_005",
    name: "Meera Suresh",
    phoneNumber: "+919876543005",
    photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400",
    photos: [
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400",
      "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400",
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400",
    ],
    bio: "Yoga instructor and Bharatanatyam dancer. Spreading positive vibes one asana at a time. Early morning person who believes sunrises are better shared. Vegetarian who makes amazing Kerala sadya.",
    gender: "FEMALE",
    location: { type: "Point", coordinates: [76.6413, 10.5276] },
    city: "Thrissur",
    dob: new Date("1997-07-28"),
    age: 27,
    height: 162,
    jobTitle: "Yoga Instructor & Dance Teacher",
    company: "Soul Studio",
    education: "BA Psychology",
    college: "Christ University, Bangalore",
    lookingFor: "LONG_TERM",
    drinking: "NEVER",
    smoking: "NEVER",
    workout: "OFTEN",
    religion: "Hindu",
    languages: ["Malayalam", "English", "Sanskrit"],
    prompts: [
      { question: "I'll know it's love when", answer: "They wake up early just to watch the sunrise with me" },
      { question: "Together we could", answer: "Travel to Rishikesh, try every cafe in Fort Kochi, and learn pottery" },
      { question: "A life goal of mine", answer: "Open a wellness retreat in the Western Ghats that's accessible to everyone" },
    ],
    interests: ["Yoga", "Dance", "Nature", "Meditation", "Ayurveda", "Vegetarian Cooking"],
    isVerified: true,
    preferences: {
      distance: 60,
      ageRange: { min: 27, max: 35 },
      gender: ["MALE"],
    },
  },
  {
    firebaseUid: "seed_user_006",
    name: "Varun Thomas",
    phoneNumber: "+919876543006",
    photoUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400",
    photos: [
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400",
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
      "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=400",
    ],
    bio: "Wildlife photographer for National Geographic. Spent 6 months documenting elephants in Wayanad. Foodie who rates cities by their street food. Looking for a travel buddy for life.",
    gender: "MALE",
    location: { type: "Point", coordinates: [77.0126, 10.8505] },
    city: "Palakkad",
    dob: new Date("1994-11-10"),
    age: 30,
    height: 182,
    jobTitle: "Wildlife Photographer",
    company: "National Geographic",
    education: "BA Visual Communication",
    college: "Loyola College, Chennai",
    lookingFor: "LONG_TERM",
    drinking: "SOMETIMES",
    smoking: "NEVER",
    workout: "OFTEN",
    religion: "Christian",
    languages: ["Malayalam", "English", "Hindi"],
    prompts: [
      { question: "The key to my heart is", answer: "Being comfortable with silence in nature and chaos in cities" },
      { question: "I'm weirdly attracted to", answer: "People who have a passport full of stamps and a camera roll full of food photos" },
      { question: "My most irrational fear", answer: "Running out of storage while capturing the perfect shot" },
    ],
    interests: ["Photography", "Wildlife", "Travel", "Food", "Trekking", "Conservation"],
    isVerified: true,
    preferences: {
      distance: 80,
      ageRange: { min: 25, max: 32 },
      gender: ["FEMALE"],
    },
  },
  {
    firebaseUid: "seed_user_007",
    name: "Lakshmi Iyer",
    phoneNumber: "+919876543007",
    photoUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400",
    photos: [
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400",
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400",
      "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400",
    ],
    bio: "Content strategist at Netflix. Bookworm who judges people by their bookshelves (sorry not sorry). Chai > Coffee always. Looking for someone to discuss plot twists and life plans with.",
    gender: "FEMALE",
    location: { type: "Point", coordinates: [76.2711, 9.9312] },
    city: "Kochi",
    dob: new Date("1999-02-14"),
    age: 25,
    height: 158,
    jobTitle: "Senior Content Strategist",
    company: "Netflix",
    education: "MA English Literature",
    college: "St. Xavier's Mumbai",
    lookingFor: "NOT_SURE",
    drinking: "SOMETIMES",
    smoking: "NEVER",
    workout: "SOMETIMES",
    religion: "Hindu",
    languages: ["Malayalam", "English", "Hindi", "Tamil"],
    prompts: [
      { question: "I'll fall for you if", answer: "You can recommend a book I haven't read and it becomes my new favorite" },
      { question: "My happy place", answer: "Any bookstore with a cafe, or my balcony with fairy lights and a good thriller" },
      { question: "Unpopular opinion", answer: "The book is NOT always better than the movie. Fight me." },
    ],
    interests: ["Reading", "Writing", "Marketing", "Theater", "Movies", "Podcasts"],
    isVerified: true,
    preferences: {
      distance: 40,
      ageRange: { min: 26, max: 33 },
      gender: ["MALE"],
    },
  },
  {
    firebaseUid: "seed_user_008",
    name: "Aditya Pillai",
    phoneNumber: "+919876543008",
    photoUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400",
    photos: [
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400",
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400",
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400",
    ],
    bio: "Film director whose short film won at IFFK. Believer in stories that make you feel. Looking for my muse, my critic, and my co-writer. Deep conversations over black coffee preferred.",
    gender: "MALE",
    location: { type: "Point", coordinates: [76.9366, 8.5241] },
    city: "Thiruvananthapuram",
    dob: new Date("1992-09-05"),
    age: 32,
    height: 176,
    jobTitle: "Film Director",
    company: "Independent",
    education: "Diploma in Film Direction",
    college: "FTII Pune",
    lookingFor: "LONG_TERM",
    drinking: "OFTEN",
    smoking: "SOMETIMES",
    workout: "NEVER",
    religion: "Hindu",
    languages: ["Malayalam", "English", "Hindi"],
    prompts: [
      { question: "I'm looking for", answer: "Someone who cries at Pixar movies and argues about Tarkovsky with equal passion" },
      { question: "Dating me is like", answer: "Being in a Mani Ratnam movie - beautiful visuals, emotional depth, and an A.R. Rahman soundtrack" },
      { question: "My creative process", answer: "3 AM ideas, endless chai, arguing with myself, and somehow a script emerges" },
    ],
    interests: ["Cinema", "Art", "Philosophy", "Music", "Writing", "Photography"],
    isVerified: true,
    preferences: {
      distance: 100,
      ageRange: { min: 25, max: 32 },
      gender: ["FEMALE"],
    },
  },
  {
    firebaseUid: "seed_user_009",
    name: "Anjali Raj",
    phoneNumber: "+919876543009",
    photoUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400",
    photos: [
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400",
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400",
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400",
    ],
    bio: "Data scientist at Amazon by day, salsa dancer by night. Can analyze your Spotify data and predict your personality. Looking for someone who can keep up on the dance floor and in debates.",
    gender: "FEMALE",
    location: { type: "Point", coordinates: [76.2711, 9.9312] },
    city: "Kochi",
    dob: new Date("1997-04-20"),
    age: 27,
    height: 167,
    jobTitle: "Senior Data Scientist",
    company: "Amazon",
    education: "MS Data Science",
    college: "Columbia University",
    lookingFor: "LONG_TERM",
    drinking: "SOMETIMES",
    smoking: "NEVER",
    workout: "OFTEN",
    religion: "Hindu",
    languages: ["Malayalam", "English", "Spanish"],
    prompts: [
      { question: "I won't shut up about", answer: "How machine learning is changing everything, the perfect bachata song, and why everyone should learn to cook" },
      { question: "Best way to ask me out", answer: "Send me an interesting dataset to analyze together (yes, I'm serious)" },
      { question: "Together we could", answer: "Take over the dance floor, build a side project, and argue about whether correlation implies causation" },
    ],
    interests: ["Dance", "Technology", "Fitness", "Travel", "Cooking", "Latin Music"],
    isVerified: true,
    preferences: {
      distance: 50,
      ageRange: { min: 28, max: 35 },
      gender: ["MALE"],
    },
  },
  {
    firebaseUid: "seed_user_010",
    name: "Karthik Nambiar",
    phoneNumber: "+919876543010",
    photoUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400",
    photos: [
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400",
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400",
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    ],
    bio: "Chef-owner of 'Spice Route' - one of Kozhikode's top restaurants. Food is my love language - I'll cook you things your grandmother would approve of. Former IT guy who followed his passion.",
    gender: "MALE",
    location: { type: "Point", coordinates: [75.7804, 11.2588] },
    city: "Kozhikode",
    dob: new Date("1991-06-12"),
    age: 33,
    height: 174,
    jobTitle: "Chef & Restaurant Owner",
    company: "Spice Route",
    education: "B.Tech + Culinary Diploma",
    college: "Le Cordon Bleu, London",
    lookingFor: "LONG_TERM",
    drinking: "SOMETIMES",
    smoking: "NEVER",
    workout: "SOMETIMES",
    religion: "Hindu",
    languages: ["Malayalam", "English", "Hindi"],
    prompts: [
      { question: "I'll cook for you", answer: "Anything from Kerala sadya to Italian risotto - just tell me your mood" },
      { question: "Biggest risk I took", answer: "Left a ₹25 LPA tech job to become a chef. Best decision ever." },
      { question: "We're a match if", answer: "You appreciate good food, don't count calories on dates, and can handle spice" },
    ],
    interests: ["Cooking", "Food", "Travel", "Business", "Wine", "Gardening"],
    isVerified: true,
    preferences: {
      distance: 75,
      ageRange: { min: 26, max: 33 },
      gender: ["FEMALE"],
    },
  },
  {
    firebaseUid: "seed_user_011",
    name: "Divya Mohan",
    phoneNumber: "+919876543011",
    photoUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400",
    photos: [
      "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400",
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400",
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400",
    ],
    bio: "Marine biologist working on coral reef conservation. TEDx speaker. Will make you care about the ocean. Looking for a partner in saving the planet - must love beaches for the right reasons.",
    gender: "FEMALE",
    location: { type: "Point", coordinates: [76.9366, 8.5241] },
    city: "Thiruvananthapuram",
    dob: new Date("1996-01-30"),
    age: 28,
    height: 163,
    jobTitle: "Marine Biologist",
    company: "CMFRI",
    education: "PhD Marine Biology",
    college: "CUSAT",
    lookingFor: "LONG_TERM",
    drinking: "SOMETIMES",
    smoking: "NEVER",
    workout: "OFTEN",
    religion: "Hindu",
    languages: ["Malayalam", "English", "Hindi"],
    prompts: [
      { question: "I'm passionate about", answer: "Ocean conservation, sustainable living, and proving that scientists can be fun at parties" },
      { question: "My ideal Sunday", answer: "Beach cleanup in the morning, scuba diving, fresh seafood lunch, documentary night" },
      { question: "Green flag", answer: "You carry your own water bottle and shopping bag without being asked" },
    ],
    interests: ["Environment", "Science", "Diving", "Hiking", "Sustainability", "Public Speaking"],
    isVerified: true,
    preferences: {
      distance: 60,
      ageRange: { min: 28, max: 36 },
      gender: ["MALE"],
    },
  },
  {
    firebaseUid: "seed_user_012",
    name: "Nikhil Sharma",
    phoneNumber: "+919876543012",
    photoUrl: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=400",
    photos: [
      "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=400",
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400",
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400",
    ],
    bio: "Classical veena player who also jams to Pink Floyd. Music teacher at a school for underprivileged kids. Contradictions make life interesting. Looking for someone who appreciates both silence and symphony.",
    gender: "MALE",
    location: { type: "Point", coordinates: [76.6413, 10.5276] },
    city: "Thrissur",
    dob: new Date("1995-10-08"),
    age: 29,
    height: 177,
    jobTitle: "Music Director & Teacher",
    company: "Harmony Foundation",
    education: "MA Carnatic Music",
    college: "Kalakshetra, Chennai",
    lookingFor: "LONG_TERM",
    drinking: "SOMETIMES",
    smoking: "NEVER",
    workout: "SOMETIMES",
    religion: "Hindu",
    languages: ["Malayalam", "English", "Hindi", "Tamil"],
    prompts: [
      { question: "I'm known for", answer: "Playing veena at temples in the morning and drums at rock shows at night" },
      { question: "Best date I can plan", answer: "Concert under the stars, followed by chai and conversations till sunrise" },
      { question: "I value", answer: "Kindness over everything. And people who can sit through a 3-hour concert without checking their phone." },
    ],
    interests: ["Music", "Concerts", "Art", "Coffee", "Teaching", "Social Work"],
    isVerified: true,
    preferences: {
      distance: 50,
      ageRange: { min: 24, max: 30 },
      gender: ["FEMALE"],
    },
  },
];

async function seed() {
  console.log("🌱 Starting seed process...");

  try {
    await connect(MONGO_URI);
    console.log("📦 Connected to MongoDB");

    const UserModel = connection.model("User", UserSchema);

    // Clear existing seed data
    const deleteResult = await UserModel.deleteMany({
      firebaseUid: { $regex: /^seed_user_/ },
    });
    console.log(`🧹 Cleared ${deleteResult.deletedCount} existing seed users`);

    // Insert new seed data
    for (const userData of dummyUsers) {
      const user = new UserModel({
        ...userData,
        isOnline: Math.random() > 0.5,
        lastSeen: new Date(Date.now() - Math.random() * 24 * 60 * 60 * 1000),
      });
      await user.save();
      console.log(`✅ Created: ${userData.name} (${userData.jobTitle} at ${userData.company})`);
    }

    console.log(`\n🎉 Successfully seeded ${dummyUsers.length} users with full profiles!`);
    console.log("\n📋 Test profiles created:\n");

    dummyUsers.forEach((u) => {
      console.log(`   👤 ${u.name}`);
      console.log(`      📍 ${u.city} | ${u.gender} | ${u.age}yo | ${u.height}cm`);
      console.log(`      💼 ${u.jobTitle} at ${u.company}`);
      console.log(`      🎓 ${u.education}, ${u.college}`);
      console.log(`      💫 ${u.interests.slice(0, 4).join(", ")}`);
      console.log(`      🔍 Looking for: ${u.lookingFor}`);
      console.log("");
    });
  } catch (error) {
    console.error("❌ Seed error:", error);
  } finally {
    await connection.close();
    console.log("👋 Disconnected from MongoDB");
  }
}

seed();
